version: '3.2'
services:
  browser1:
     build: .
     command: sh -c '/app/dc_entry.sh'
     working_dir: /app
     stdin_open: true
     tty: true
     ports:
       - "5800:5900"
     environment:
        - VNC_SERVER_PASSWORD=secret
        # +15d or -6d
        - FAKETIME=+10d
     shm_size: 1g
     user: puppy
#   browser2:
#      build: .
#      command: sh -c '/app/dc_entry.sh'
#      working_dir: /app
#      stdin_open: true
#      tty: true
#      ports:
#        - "5900:5900"
#      environment:
#         - VNC_SERVER_PASSWORD=secret
#         # +15d or -6d
#         - FAKETIME=+10d
#      shm_size: 1g
#      user: puppy
